### GENERAL VARIABLES ###

# Mandatory files
singularity_image: "/storage/replicated/cirad/projects/GE2POP/2023_LRR/LRRtransfer_image/v2_20250407/LRRtransfer.sif"
target_genome:     "/storage/replicated/cirad_users/girodollej/2024_LRR/03_scripts/LRRtransfer/GeneModelTransfer/example/Punctata_chr1.fasta"
ref_genome:        "/storage/replicated/cirad_users/girodollej/2024_LRR/03_scripts/LRRtransfer/GeneModelTransfer/example/Nipponbare_chr1.fasta"
ref_gff:           "/storage/replicated/cirad_users/girodollej/2024_LRR/03_scripts/LRRtransfer/GeneModelTransfer/example/Nipponbare_LRR-CR_chr1.gff"
ref_locus_info:    "/storage/replicated/cirad_users/girodollej/2024_LRR/03_scripts/LRRtransfer/GeneModelTransfer/example/Info_locus_Nipponbare.txt"
CL_min_sim: "0"
IGNORE_EXONERATE_ERRORS: "true"

# optional folder containing a prebuild LRROME
lrrome:            ""
OUTPUTS_DIRNAME: "LRR_TRANSFERT_OUTPUTS"
