__default__:
    mem-per-cpu: 5G
    partition: agap_normal
    job-name: LRRtransfer.{rule}
    output: LRRtransfer.{rule}.%j.err
    error:  LRRtransfer.{rule}.%j.out

genePrediction:
    partition: agap_short
    job-name: LRRtransfer.{rule}.{wildcards.split_id}
    output: LRRtransfer.{rule}.{wildcards.split_id}.%j.err
    error:  LRRtransfer.{rule}.{wildcards.split_id}.%j.out
